default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: store_user
  password: admin
  host: localhost

development:
  <<: *default
  database: book_store_dev

test:
  <<: *default
  database: book_store_test

production:
  <<: *default
  database: book_store
