# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f163b98bad7863aa0eb109fb1e7f607876fa91fb7ba7664064d4f7c2f400c6ae6455ccf0509c22216129b05029eabd72eaaefdea2e27c3b9cff0009f95cb9c0f

test:
  secret_key_base: 9b89283d62d790c909a0aea3900958d4946e4815d0db62cc1b470da39aa28936615bf9061da7c925f1d696d1449e7902ebc2b3926b2bf4817b5fe15a71fd3a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV['SECRET_KEY_BASE']
